# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: mainflux
description: Mainflux IoT Platform
icon: https://avatars1.githubusercontent.com/u/13207490
type: application
version: 0.1.6
appVersion: "0.11.0"
home: https://www.mainflux.com
sources:
  - https://hub.docker.com/u/mainflux/
maintainers:
  - name: isavcic
    email: isavcic@gmail.com

dependencies:
  - name: nats
    version: "4.2.6"
    repository: "@stable"
  - name: redis
    version: "9.5.5"
    repository: "@stable"
    alias: redis-streams
  - name: redis
    version: "9.5.5"
    repository: "@stable"
    alias: redis-auth
  - name: redis
    version: "9.5.5"
    repository: "@stable"
    alias: redis-mqtt
  - name: redis
    version: "9.5.5"
    repository: "@stable"
    alias: redis-opcua
    condition: adapter_opcua.enabled
  - name: redis
    version: "9.5.5"
    repository: "@stable"
    alias: redis-lora
    condition: adapter_lora.enabled
  - name: influxdb
    version: "4.3.2"
    repository: "@stable"
    condition: influxdb.enabled
  - name: mongodb
    version: "7.8.10"
    repository: "@stable"
    alias: twins-db
    condition: twins.enabled
